name: patch-posts.yml
on:
    push:
        branches:
            - main

jobs:
    patch-posts:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: '2'

            -   name: Set up Cloud SDK
                uses: google-github-actions/setup-gcloud@v2

            -   name: Authenticate to GCP
                id: auth
                uses: google-github-actions/auth@v2
                with:
                    credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
                    project_id: ${{ secrets.PROJECT_ID }}

            -   name: Install jq
                run: sudo apt-get update && sudo apt-get install -y jq

            -   name: Make script executable
                run: chmod +x .github/workflows/patcher.sh

            -   name: Run script
                with:
                    GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
                    API_KEY: ${{ secrets.API_KEY }}
                    PATCH_ENDPOINT: ${{ secrets.PATCH_ENDPOINT }}

                run: ./.github/workflows/patcher.sh "$GCS_BUCKET" "$API_KEY" "$PATCH_ENDPOINT"
